spring.datasource.url=jdbc:postgresql://localhost:5432/appliance_store
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-exception=false
server.error.include-stacktrace=never

logging.level.org.spring.finalproject=INFO

jwt.secret=${JWT_SECRET}
